Documentation
PowerShell/Win32-OpenSSH pull request #1366
Opened 2019-04-08 22:56 UTC by jsoref

Help people find their way to the wiki and build instructions.

2019-04-08 23:09 UTC, jsoref commented
This supersedes #1294 by @maertendMSFT  -- it's unfortunate that wasn't merged a while ago.

2019-04-21 21:37 UTC, ghost approved these changes

2019-04-21 21:37 UTC, ghost approved these changes

2020-09-17 16:31 UTC, floh96 requested changes
As of Nov 1st 2016, active development on "Windows for OpenSSH" is being done in https://github.com/PowerShell/openssh-portable. 

This repo (https://github.com/PowerShell/Win32-OpenSSH) is being maintained to keep track of releases and issues. The [Documentation](https://github.com/PowerShell/Win32-OpenSSH/wiki) for the project is also maintained here in the wiki. 

### Release History:
| Date | Version | Release with source |
|---|---|---|
| 7/26/2018 | 7.7.2.0 | https://github.com/PowerShell/openssh-portable/releases/tag/v7.7.2.0 |
| 1/11/2019 | 7.9.0.0 | https://github.com/PowerShell/openssh-portable/releases/tag/v7.9.0.0 |
| 6/23/2019 | 8.0.0.0 | https://github.com/PowerShell/openssh-portable/releases/tag/v8.0.0.0 |
| 12/17/2019 | 8.1.0.0 | https://github.com/PowerShell/openssh-portable/releases/tag/v8.1.0.0 |

2021-05-04 21:37 UTC, bagajjal commented
Closing this PR.. Readme is already updated.

https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/README

2021-05-04 21:37 UTC, closed without merging